version: '3.8'
services:
  db:
    image: postgres:16.4
    container_name: container_promotoras_bdd
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: promotoras_bdd
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pgdata:
